### ISSUE TITLE
Trying to run on Mac

### ISSUE THREAD

**Issue by danieldocki** [nebelorz/NST-medivia-bot#4]
I have no knowledge of pyhton, but I managed to run it on Mac OS, but I had to remove the pydirectinput lib because it only works on Windows.

I don't know if it's working, I focused on running it only, do you know if there is a way to replace pydirectinput with another lib that works on Mac and Windows?

<img width="846" alt="Screenshot 2023-09-13 at 22 12 38" src="https://github.com/nebelorz/NST-medivia-bot/assets/10542/c4c37bc6-cb0a-4ed4-a2e8-f486327adab2">

**Comment by nebelorz** [comment]
Hi there! I believe pyautogui should work on Mac, so maybe if you replace all the pyDI methods with pyAG it will work and pydirectinput will not be needed anymore.Both pydirectinput and pyautogui libraries have mouse and keyboard inputs, but I have used both due to some problem I've got, which I cannot recall now xD. Try it and tell me if you got it running please! If you do, I'll try to update it to only use pyautogui 🙃
